// Default Role Templates derived from 'neointeraction' tenant
module.exports = {
  Accountant: {
    name: "Accountant",
    description: "Accountant",
    modules: ["payroll", "organization", "my_journey"],
    permissions: [
      "payroll:view_payslips",
      "payroll:process",
      "payroll:view",
      "organization:view",
      "employees:view",
      "my_journey:view",
    ],
  },
  Admin: {
    name: "Admin",
    description: "Admin",
    modules: [
      "employees",
      "roles",
      "assets",
      "audit",
      "leave",
      "projects",
      "organization",
      "feedback",
      "timesheet",
      "policies",
      "documents",
      "email_automation",
      "ai_chatbot",
      "attendance",
      "payroll",
      "social",
      "shifts",
      "exit_management",
      "designations",
      "help",
      "clients",
    ],
    permissions: [
      "employees:view",
      "employees:create",
      "employees:edit",
      "employees:delete",
      "employees:manage_documents",
      "roles:view",
      "roles:create",
      "roles:edit",
      "roles:delete",
      "attendance:view",
      "attendance:check_in_out",
      "attendance:manage",
      "attendance:regularize",
      "shifts:view",
      "shifts:manage",
      "shifts:assign",
      "leave:view",
      "leave:apply",
      "leave:approve",
      "leave:manage_policies",
      "leave:manage_balances",
      "payroll:view",
      "payroll:manage_structure",
      "payroll:process",
      "payroll:view_payslips",
      "projects:view",
      "projects:create",
      "projects:edit",
      "projects:manage_members",
      "timesheet:view",
      "timesheet:submit",
      "timesheet:approve",
      "organization:view",
      "organization:manage",
      "assets:view",
      "assets:add",
      "assets:allocate",
      "assets:manage_categories",
      "documents:view",
      "documents:upload",
      "documents:delete",
      "audit:view",
      "social:view",
      "social:post",
      "social:comment",
      "social:moderate",
      "feedback:view_received",
      "feedback:submit",
      "appreciation:view",
      "appreciation:give",
      "email_automation:manage",
      "ai_chatbot:manage",
      "leave:view_all",
      "designations:view",
      "designations:manage",
      "exit_management:view",
      "exit_management:process",
      "exit_management:manage",
      "clients:view",
      "clients:create",
      "clients:edit",
      "clients:delete",
    ],
  },
  CEO: {
    name: "CEO",
    description: "CEO",
    modules: ["social"],
    permissions: [],
  },
  Consultant: {
    name: "Consultant",
    description: "Consultant",
    modules: [
      "assets",
      "leave",
      "projects",
      "organization",
      "timesheet",
      "my_journey",
      "attendance",
      "payroll",
    ],
    permissions: [
      "my_journey:view",
      "attendance:view",
      "attendance:check_in_out",
      "attendance:manage",
      "attendance:regularize",
      "payroll:view_payslips",
    ],
  },
  Employee: {
    name: "Employee",
    description: "Employee",
    modules: [
      "assets",
      "leave",
      "organization",
      "feedback",
      "timesheet",
      "documents",
      "payroll",
      "social",
      "attendance",
      "appreciation",
      "projects",
      "my_journey",
    ],
    permissions: [
      "leave:view",
      "leave:apply",
      "projects:view",
      "projects:task_view",
      "projects:task_edit",
      "projects:task_assign",
      "projects:task_delete",
      "projects:task_create",
      "my_journey:view",
    ],
  },
  HR: {
    name: "HR",
    description: "HR",
    modules: [
      "employees",
      "assets",
      "leave",
      "organization",
      "feedback",
      "timesheet",
      "policies",
      "documents",
      "attendance",
      "email_automation",
      "social",
      "payroll",
      "ai_chatbot",
      "appreciation",
      "shifts",
      "my_journey",
      "designations",
      "exit_management",
      "clients",
      "help",
    ],
    permissions: [
      "designations:view",
      "designations:manage",
      "employees:view",
      "employees:create",
      "employees:edit",
      "employees:delete",
      "employees:manage_documents",
      "exit_management:view",
      "exit_management:process",
      "clients:view",
      "clients:create",
      "clients:delete",
      "clients:edit",
      "my_journey:view",
      "help:view",
      "help:manage",
      "leave:view",
      "leave:apply",
      "leave:approve",
      "leave:manage_policies",
      "leave:manage_balances",
      "leave:view_all",
      "shifts:view",
      "shifts:assign",
      "shifts:manage",
      "payroll:manage_structure",
      "payroll:view_payslips",
      "payroll:view",
    ],
  },
  Intern: {
    name: "Intern",
    description: "Intern",
    modules: [
      "assets",
      "leave",
      "projects",
      "organization",
      "feedback",
      "timesheet",
      "documents",
      "my_journey",
    ],
    permissions: ["my_journey:view", "assets:view"],
  },
  "Project Manager": {
    name: "Project Manager",
    description: "Project Manager",
    modules: [
      "employees",
      "roles",
      "assets",
      "ai_chatbot",
      "audit",
      "attendance",
      "payroll",
      "projects",
      "organization",
      "feedback",
      "social",
      "email_automation",
      "timesheet",
      "timesheet",
      "policies",
      "documents",
      "appreciation",
      "shifts",
      "my_journey",
      "clients",
      "leave",
    ],
    permissions: [
      "clients:view",
      "clients:create",
      "clients:edit",
      "clients:delete",
      "my_journey:view",
      "leave:view",
      "leave:apply",
      "leave:approve",
      "leave:manage_balances",
      "leave:view_all",
    ],
  },
};
